### ISSUE TITLE
COA tidak muncul saat di search

### ISSUE THREAD

**Issue by LAURENANGELIEM1** [Adiantzo/https-github.com-bugs-msn-bugs-issues-1075#1]
dear IT,
 COA hutang dagang lain lain H04000021090199, COA sudah ada dari dulu tp ketika mau melakukan payment COA tersebut tidak muncul ketika di search pada book Indonesia Satu Berniaga
![ISB](https://github.com/user-attachments/assets/2d23e94b-1a47-4a94-bf1f-89100222a798)

**Comment by YENNIM1** [comment]
tolong dibantu ya, thx
